### ISSUE TITLE
Problem with login_user and login_password when root password is changed

### ISSUE THREAD

**Issue by yannikmesserli** [ANXS/mysql#23]
When changing the root password, i.e. `mysql_root_db_pass: root`, this issue is raised when the playbook is not run for the first time:

```
failed: [default] => {"failed": true}
msg: unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials
```

(Happened with vagrant)

The issue might be solved by modifying the `mysql_db` and `mysql_user` call like this:

```
mysql_db:
        login_user: root
        login_password: "{{mysql_root_password}}"
        ...
```

But probably some modifications are required to take into account when it's the first time the playbook is run.

Hope it helps
