### ISSUE TITLE
Get rid of the `mysql_current_root_password` 'single-use variable'

### ISSUE THREAD

**Issue by boosh** [ANXS/mysql#33]
The use of `mysql_current_root_password` as a 'single-use variable' is bad. The whole point of ansible is that plays are idempotent. Having to remember to edit a vars file to comment/uncomment a variable each time the play is run on a new server will lead to frustration, errors and mistakes.

A better approach would be something like this:
In `default/main.yml`
```
mysql_default_root_password: ''
```

In `tasks/secure.yml`
```
- name: MySQL | Test whether the root password has already been changed.
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost
  register: root_pw_already_set
  ignore_errors: yes

- name: MySQL | Changing the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_default_root_password}}"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost
  when: "'failed' in root_pw_already_set"
```

This will first test whether the root pw has been changed, and will only then change it by supplying the default if it hasn't been. There's no need to comment out variables for this to work. 

This also lets users cycle root passwords when they want (which I don't think should be done here anyway) by just setting a custom value for `mysql_default_root_password`.
