### ISSUE TITLE
Representation of MySQL settings as a dictionary

### ISSUE THREAD

**Issue by AndreiPashkin** [ANXS/mysql#7]
Hi!
There is a lot of settings in MySQL, and only subset of them are configurable in this role - I think its reasonable to make variable which would be a dictionary, with keys representing config sections and values - dictionaries with settings and values. Like:

``` yaml
mysqld:
  key_buffer: '16K'
  max_allowed_packet : '1M'
  thread_stack: '64K'
client:
  port: 3307
```

it needs to be merged with similar dictionary from default vars.
